### ISSUE TITLE
共享SummerTTS的DLL

### ISSUE THREAD

**Issue by liaiwu** [aiaimimi0920/godot-tts#2]
能否将您编译成功的SummerTTS的DLL共享一下,非常感谢!

**Comment by aiaimimi0920** [comment]
我应该已经把方法在summertts的项目里面写了：https://github.com/huakunyang/SummerTTS/issues/35

我无法给你提供原生的只包含summertts项目的dll，因为我基本上是将其全部代码复制编译到我的项目中，所以如果你需要原始的只包含dll的代码，那么你可以按照我的方法编译一下。

十分抱歉，过春节，没有及时回复你得消息
@liaiwu
